prefix_prompt_templates = {
    "food": "Answer the given question related to food items in a country. Generate only the name of the food items. Do not output any extra text.",
    "house": "Answer the given question related to house numbers in a country. Generate only the house number. Do not output any extra text.",
    "religious_denominations": "Answer the given question related to religious denominations in a country. Generate only the name of the religious denominations. Do not output any extra text.",
    "languages": "Answer the given question related to languages in a country. Generate only the name of the languages or dialects. Do not output any extra text.",
    "national": "Answer the given question related to food items in a country. Generate only the name of the food item. Do not output any extra text.",
    "religions": "Answer the given question related to religions in a country. Generate only the name of the religions. Do not output any extra text.",
    "currency": "Answer the given question related to currency in a country. Generate only the name of the currency. Do not output any extra text.",
    "holidays": "Answer the given question related to holidays in a country. Generate only the name of the holidays. Do not output any extra text.",
}

prefix_mapping = {
    "health": "food",
    "convenience": "food",
    "familiarity": "food",
    "national": "national",
    "house": "house",
    "religious_denominations": "religious_denominations",
    "languages": "languages",
    "religions": "religions",
    "currency": "currency",
    "holidays": "holidays",
}

prompt_templates = {
    "languages_0": "The major languages spoken in {country} are ",
    "languages_1": "The prominent languages in {country} include ",
    "languages_2": "In {country}, the most common spoken languages are ",
    "convenience_0": "The food in {country} that is easy to prepare is ",
    "convenience_2": "The food in {country} that takes no time to prepare is ",
    "convenience_3": "The food in {country} that can be bought in shops close to where someone lives or works is ",
    "familiarity_0": "The food in {country} that people usually eat is ",
    "familiarity_1": "The food in {country} that is familiar is ",
    "familiarity_2": "The food in {country} that is like the food someone ate when they were a child is ",
    "health_1": "The food in {country} that keeps someone healthy is ",
    "health_2": "The nutritious food in {country} is ",
    "health_4": "The food in {country} that is good for someone's skin/teeth/hair/nails etc is ",
    "house_0": "The typical house numbers in {country} are ",
    "house_1": "The most common house numbers in {country} are ",
    "house_2": "In {country}, the house numbers that are frequently used are ",
    "national_0": "The national food of {country} is ",
    "national_1": "The national dish of {country} is ",
    "national_2": "In {country}, the national food is ",
    "religions_0": "The major religions practiced in {country} are ",
    "religions_1": "The prominent religions in {country} include ",
    "religions_2": "In {country}, the most common religions are ",
    "currency_0": "The currency used in {country} is ",
    "currency_1": "The official currency of {country} is ",
    "currency_2": "In {country}, the currency in circulation is ",
    "holidays_0": "The holidays celebrated in {country} include ",
    "holidays_1": "In {country}, the celebrated holidays are ",
    "holidays_2": "The holidays observed in {country} include ",
}
